Fix nested refs when running sync
json-schema-faker/json-schema-faker pull request #666
Opened 2021-07-12 05:58 UTC by starsprung

json-schema-faker currently doesn't follow nested `$ref`s correct when using `generate`.

Current behaviour:

```
  1) nested $refs (tests/schema/core/issues/nested-refs.json)
       should follow nested $refs in synchronous mode:

      AssertionError: expected { hello: {} } to deeply equal { hello: 'world!' }
      + expected - actual

       {
      -  "hello": {}
      +  "hello": "world!"
       }
```

This only happens when running `generate`, `resolve` doesn't have this issue.

2021-07-12 14:47 UTC, pateketrueke requested changes
Awesome! But it can be simplified, right?

I noticed this produces the same exact result:

```diff
diff --git a/src/lib/core/buildResolveSchema.js b/src/lib/core/buildResolveSchema.js
index c713d1f..133943f 100644
--- a/src/lib/core/buildResolveSchema.js
+++ b/src/lib/core/buildResolveSchema.js
@@ -63,17 +63,19 @@ const buildResolveSchema = ({
         ref = utils.getLocalRef(schema, sub.$ref, synchronous && refs) || null;
       }

+      let fixed;
       if (typeof ref !== 'undefined') {
         if (!ref && optionAPI('ignoreMissingRefs') !== true) {
           throw new Error(`Reference not found: ${sub.$ref}`);
         }

+        fixed = true;
         seenRefs[sub.$ref] -= 1;
         utils.merge(sub, ref || {});
       }

       // just remove the reference
-      delete sub.$ref;
+      if (!fixed) delete sub.$ref;
       return sub;
     }
```

2021-07-12 16:42 UTC, starsprung commented
Can `ref` ever be `null` here?

```
         fixed = ref.$ref;
         seenRefs[sub.$ref] -= 1;
         utils.merge(sub, ref || {});
```

the `ref || {}` made me a big nervous about the possible values.

2021-07-12 18:39 UTC, pateketrueke commented
Certainly it can be null, we could try `fixed = ref && ref.$ref;` instead?

2021-07-12 20:30 UTC, starsprung commented
Cool, I've updated it.

2021-07-13 13:27 UTC, pateketrueke approved these changes

2021-07-13 13:44 UTC, merged